# Generated by Django 5.2.7 on 2025-10-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_alter_pokemonentity_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
